Repository clojure-garden/clojure-garden, pull requests merged in 2021-12, with the labels that each got.

#3 Add GitHub Actions CD workflow
  .github/workflows/cd.yaml
  bb.edn
  deployment/images/backend/Dockerfile
Labels: devops

#4 Add deploy to DigitalOcean
  .github/workflows/digitalocean.yaml
  deployment/digitalocean/backend/Dockerfile
  deployment/digitalocean/docker-compose.yaml
Labels: enhancement, devops

#5 Release v0.1.21
  .github/workflows/cd.yaml
  .github/workflows/ci-backend.yaml
  .github/workflows/digitalocean.yaml
Labels: enhancement, devops

#8 Remove unnecessary steps
  .github/workflows/ci-backend.yaml
Labels: backend, devops

#9 [frontend] Add Dockerfile
  .github/workflows/cd.yaml
  bb.edn
  deployment/images/frontend/Dockerfile
Labels: frontend, devops

#12 Fix metabase port mapping
  deployment/digitalocean/proxy/etc/service.conf
Labels: devops

#15 Move `pull_request_template.md`
  .github/pull_request_template.md
Labels: bug, documentation

#17 Fix the issue template chooser config
  .github/ISSUE_TEMPLATE/config.yaml
Labels: documentation, enhancement

#18 Fix the .yaml extension
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/workflows/cd.yml
  .github/workflows/ci-backend.yml
  .github/workflows/ci-frontend.yml
  .github/workflows/digitalocean.yml
  README.md
  bb.edn
  codecov.yml
  deployment/digitalocean/docker-compose.yml
  deployment/local/docker-compose.yml
Labels: enhancement

#19 Fix the contact headers
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#20 Add a release label
  README.md
Labels: enhancement
